---
- hosts: all

  vars:
    user: phillipalexander
    home_dir: "/Users/{{ user }}"
    application_dir: "{{ home_dir }}/Applications"
    caskroom_dir: /opt/homebrew-cask/Caskroom
    zsh_path: /usr/local/bin/zsh
    user_lib: "/Users/{{ user }}/Library"
    user_lib_prefs: "{{ user_lib }}/Preferences"
    homebrew_cask_packages:
      - alfred
      - flux
      - firefox
      - google-chrome
      - google-chrome-canary
      - handbrake
      - hipchat
      - vlc
      - brackets
      - notational-velocity
      - dash
      - kaleidoscope
      - appcleaner
      - google-drive
      - sublime-text3
      - transmission
      - vmware-fusion
      - clamxav
      - evernote
      - makerware
      - screenflow
      - slate
      - amethyst
      - karabiner
      - mou
      - recordit
      - dropbox
      - graphsketcher
    homebrew_packages:
      - ack
      - hub
      - zsh
      - mongodb
      - figlet
      - sqlite
      - tree
      - wget
      - htop
      - tmux
      - fasd
      - ssh-copy-id
      - node
      - redis
    npm_modules:
      - node-inspector
      - node-theseus
      - yo
      - generator-commander
      - mocha
      - hubot
      - coffee-script
      - grunt
      - azure-cli

  tasks:
      - include_tasks: tasks/homebrew.yml
        tags: homebrew
      - include_tasks: tasks/npm.yml
        tags: npm
      # - include_tasks: tasks/files.yml
      #   tags: files
      # - include_tasks: tasks/vim.yml
      #   tags: vim
      # - include_tasks: tasks/zsh.yml
      #   tags: zsh

