---

- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: yes

- name: Install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_packages }}"

- name: Tap homebrew cask
  homebrew_tap:
    tap: homebrew/cask
    state: present

- name: Tap homebrew cask versions
  homebrew_tap:
    tap: homebrew/cask-versions
    state: present

# - name: Install homebrew cask
#   homebrew: name=brew-cask

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items: "{{ homebrew_cask_packages }}"
