---
- name: Download spf13-vim installer
  get_url:
    url: https://j.mp/spf13-vim3
    dest: /tmp/spf13-vim.sh
    mode: "0755"

- name: Install spf13-vim configuration
  command: sh /tmp/spf13-vim.sh
